// Sport configuration types for multi-sport support

export type SportType = 'team' | 'individual';
export type RecordFormat = 'W-L' | 'W-L-T' | 'W-L-OTL' | 'points' | 'none';
export type SportCategory = 'pro' | 'college' | 'soccer' | 'individual';

export interface SportConfig {
  id: string;
  name: string;
  shortName: string;
  icon: string;
  category: SportCategory;
  type: SportType;
  apiPath: {
    sport: string;
    league: string;
  };
  periodLabel: string;
  periodLabelPlural: string;
  recordFormat: RecordFormat;
  hasTeams: boolean;
  hasFavorites: boolean;
  scoreLabel: string;
  periods: string[];
  overtimeLabel: string;
}

// All available sports configurations
export const SPORTS_CONFIG: Record<string, SportConfig> = {
  // ===== PRO TEAM SPORTS =====
  nfl: {
    id: 'nfl',
    name: 'NFL Football',
    shortName: 'NFL',
    icon: '🏈',
    category: 'pro',
    type: 'team',
    apiPath: { sport: 'football', league: 'nfl' },
    periodLabel: 'Quarter',
    periodLabelPlural: 'Quarters',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Points',
    periods: ['1st', '2nd', '3rd', '4th'],
    overtimeLabel: 'OT',
  },
  nba: {
    id: 'nba',
    name: 'NBA Basketball',
    shortName: 'NBA',
    icon: '🏀',
    category: 'pro',
    type: 'team',
    apiPath: { sport: 'basketball', league: 'nba' },
    periodLabel: 'Quarter',
    periodLabelPlural: 'Quarters',
    recordFormat: 'W-L',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Points',
    periods: ['1st', '2nd', '3rd', '4th'],
    overtimeLabel: 'OT',
  },
  wnba: {
    id: 'wnba',
    name: 'WNBA Basketball',
    shortName: 'WNBA',
    icon: '🏀',
    category: 'pro',
    type: 'team',
    apiPath: { sport: 'basketball', league: 'wnba' },
    periodLabel: 'Quarter',
    periodLabelPlural: 'Quarters',
    recordFormat: 'W-L',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Points',
    periods: ['1st', '2nd', '3rd', '4th'],
    overtimeLabel: 'OT',
  },
  mlb: {
    id: 'mlb',
    name: 'MLB Baseball',
    shortName: 'MLB',
    icon: '⚾',
    category: 'pro',
    type: 'team',
    apiPath: { sport: 'baseball', league: 'mlb' },
    periodLabel: 'Inning',
    periodLabelPlural: 'Innings',
    recordFormat: 'W-L',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Runs',
    periods: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
    overtimeLabel: 'Extra Innings',
  },
  nhl: {
    id: 'nhl',
    name: 'NHL Hockey',
    shortName: 'NHL',
    icon: '🏒',
    category: 'pro',
    type: 'team',
    apiPath: { sport: 'hockey', league: 'nhl' },
    periodLabel: 'Period',
    periodLabelPlural: 'Periods',
    recordFormat: 'W-L-OTL',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st', '2nd', '3rd'],
    overtimeLabel: 'OT',
  },
  mls: {
    id: 'mls',
    name: 'MLS Soccer',
    shortName: 'MLS',
    icon: '⚽',
    category: 'pro',
    type: 'team',
    apiPath: { sport: 'soccer', league: 'usa.1' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'Extra Time',
  },
  nwsl: {
    id: 'nwsl',
    name: 'NWSL Soccer',
    shortName: 'NWSL',
    icon: '⚽',
    category: 'pro',
    type: 'team',
    apiPath: { sport: 'soccer', league: 'usa.nwsl' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'Extra Time',
  },

  // ===== COLLEGE SPORTS =====
  cfb: {
    id: 'cfb',
    name: 'College Football',
    shortName: 'CFB',
    icon: '🏈',
    category: 'college',
    type: 'team',
    apiPath: { sport: 'football', league: 'college-football' },
    periodLabel: 'Quarter',
    periodLabelPlural: 'Quarters',
    recordFormat: 'W-L',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Points',
    periods: ['1st', '2nd', '3rd', '4th'],
    overtimeLabel: 'OT',
  },
  mcbb: {
    id: 'mcbb',
    name: "Men's College Basketball",
    shortName: 'MCBB',
    icon: '🏀',
    category: 'college',
    type: 'team',
    apiPath: { sport: 'basketball', league: 'mens-college-basketball' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Points',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'OT',
  },
  wcbb: {
    id: 'wcbb',
    name: "Women's College Basketball",
    shortName: 'WCBB',
    icon: '🏀',
    category: 'college',
    type: 'team',
    apiPath: { sport: 'basketball', league: 'womens-college-basketball' },
    periodLabel: 'Quarter',
    periodLabelPlural: 'Quarters',
    recordFormat: 'W-L',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Points',
    periods: ['1st', '2nd', '3rd', '4th'],
    overtimeLabel: 'OT',
  },

  // ===== INTERNATIONAL SOCCER =====
  epl: {
    id: 'epl',
    name: 'English Premier League',
    shortName: 'EPL',
    icon: '⚽',
    category: 'soccer',
    type: 'team',
    apiPath: { sport: 'soccer', league: 'eng.1' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'Extra Time',
  },
  laliga: {
    id: 'laliga',
    name: 'La Liga',
    shortName: 'La Liga',
    icon: '⚽',
    category: 'soccer',
    type: 'team',
    apiPath: { sport: 'soccer', league: 'esp.1' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'Extra Time',
  },
  bundesliga: {
    id: 'bundesliga',
    name: 'Bundesliga',
    shortName: 'Bundesliga',
    icon: '⚽',
    category: 'soccer',
    type: 'team',
    apiPath: { sport: 'soccer', league: 'ger.1' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'Extra Time',
  },
  seriea: {
    id: 'seriea',
    name: 'Serie A',
    shortName: 'Serie A',
    icon: '⚽',
    category: 'soccer',
    type: 'team',
    apiPath: { sport: 'soccer', league: 'ita.1' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'Extra Time',
  },
  ligue1: {
    id: 'ligue1',
    name: 'Ligue 1',
    shortName: 'Ligue 1',
    icon: '⚽',
    category: 'soccer',
    type: 'team',
    apiPath: { sport: 'soccer', league: 'fra.1' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'Extra Time',
  },
  ucl: {
    id: 'ucl',
    name: 'UEFA Champions League',
    shortName: 'UCL',
    icon: '⚽',
    category: 'soccer',
    type: 'team',
    apiPath: { sport: 'soccer', league: 'uefa.champions' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'Extra Time',
  },
  ligamx: {
    id: 'ligamx',
    name: 'Liga MX',
    shortName: 'Liga MX',
    icon: '⚽',
    category: 'soccer',
    type: 'team',
    apiPath: { sport: 'soccer', league: 'mex.1' },
    periodLabel: 'Half',
    periodLabelPlural: 'Halves',
    recordFormat: 'W-L-T',
    hasTeams: true,
    hasFavorites: true,
    scoreLabel: 'Goals',
    periods: ['1st Half', '2nd Half'],
    overtimeLabel: 'Extra Time',
  },

  // ===== INDIVIDUAL SPORTS =====
  pga: {
    id: 'pga',
    name: 'PGA Golf',
    shortName: 'PGA',
    icon: '⛳',
    category: 'individual',
    type: 'individual',
    apiPath: { sport: 'golf', league: 'pga' },
    periodLabel: 'Round',
    periodLabelPlural: 'Rounds',
    recordFormat: 'none',
    hasTeams: false,
    hasFavorites: true,
    scoreLabel: 'Score',
    periods: ['R1', 'R2', 'R3', 'R4'],
    overtimeLabel: 'Playoff',
  },
  lpga: {
    id: 'lpga',
    name: 'LPGA Golf',
    shortName: 'LPGA',
    icon: '⛳',
    category: 'individual',
    type: 'individual',
    apiPath: { sport: 'golf', league: 'lpga' },
    periodLabel: 'Round',
    periodLabelPlural: 'Rounds',
    recordFormat: 'none',
    hasTeams: false,
    hasFavorites: true,
    scoreLabel: 'Score',
    periods: ['R1', 'R2', 'R3', 'R4'],
    overtimeLabel: 'Playoff',
  },
  atp: {
    id: 'atp',
    name: 'ATP Tennis',
    shortName: 'ATP',
    icon: '🎾',
    category: 'individual',
    type: 'individual',
    apiPath: { sport: 'tennis', league: 'atp' },
    periodLabel: 'Set',
    periodLabelPlural: 'Sets',
    recordFormat: 'none',
    hasTeams: false,
    hasFavorites: true,
    scoreLabel: 'Games',
    periods: ['Set 1', 'Set 2', 'Set 3', 'Set 4', 'Set 5'],
    overtimeLabel: 'Tiebreak',
  },
  wta: {
    id: 'wta',
    name: 'WTA Tennis',
    shortName: 'WTA',
    icon: '🎾',
    category: 'individual',
    type: 'individual',
    apiPath: { sport: 'tennis', league: 'wta' },
    periodLabel: 'Set',
    periodLabelPlural: 'Sets',
    recordFormat: 'none',
    hasTeams: false,
    hasFavorites: true,
    scoreLabel: 'Games',
    periods: ['Set 1', 'Set 2', 'Set 3'],
    overtimeLabel: 'Tiebreak',
  },
  f1: {
    id: 'f1',
    name: 'Formula 1',
    shortName: 'F1',
    icon: '🏎️',
    category: 'individual',
    type: 'individual',
    apiPath: { sport: 'racing', league: 'f1' },
    periodLabel: 'Lap',
    periodLabelPlural: 'Laps',
    recordFormat: 'points',
    hasTeams: false,
    hasFavorites: true,
    scoreLabel: 'Points',
    periods: [],
    overtimeLabel: '',
  },
  nascar: {
    id: 'nascar',
    name: 'NASCAR',
    shortName: 'NASCAR',
    icon: '🏁',
    category: 'individual',
    type: 'individual',
    apiPath: { sport: 'racing', league: 'nascar-cup' },
    periodLabel: 'Lap',
    periodLabelPlural: 'Laps',
    recordFormat: 'points',
    hasTeams: false,
    hasFavorites: true,
    scoreLabel: 'Points',
    periods: [],
    overtimeLabel: '',
  },
  indycar: {
    id: 'indycar',
    name: 'IndyCar',
    shortName: 'IndyCar',
    icon: '🏎️',
    category: 'individual',
    type: 'individual',
    apiPath: { sport: 'racing', league: 'irl' },
    periodLabel: 'Lap',
    periodLabelPlural: 'Laps',
    recordFormat: 'points',
    hasTeams: false,
    hasFavorites: true,
    scoreLabel: 'Points',
    periods: [],
    overtimeLabel: '',
  },
  ufc: {
    id: 'ufc',
    name: 'UFC',
    shortName: 'UFC',
    icon: '🥊',
    category: 'individual',
    type: 'individual',
    apiPath: { sport: 'mma', league: 'ufc' },
    periodLabel: 'Round',
    periodLabelPlural: 'Rounds',
    recordFormat: 'W-L',
    hasTeams: false,
    hasFavorites: true,
    scoreLabel: 'Decision',
    periods: ['R1', 'R2', 'R3', 'R4', 'R5'],
    overtimeLabel: '',
  },
  boxing: {
    id: 'boxing',
    name: 'Boxing',
    shortName: 'Boxing',
    icon: '🥊',
    category: 'individual',
    type: 'individual',
    apiPath: { sport: 'boxing', league: 'boxing' },
    periodLabel: 'Round',
    periodLabelPlural: 'Rounds',
    recordFormat: 'W-L',
    hasTeams: false,
    hasFavorites: true,
    scoreLabel: 'Decision',
    periods: [],
    overtimeLabel: '',
  },
};

// Helper functions
export function getSportConfig(sportId: string): SportConfig | undefined {
  return SPORTS_CONFIG[sportId];
}

export function getSportsByCategory(category: SportCategory): SportConfig[] {
  return Object.values(SPORTS_CONFIG).filter(sport => sport.category === category);
}

export function getTeamSports(): SportConfig[] {
  return Object.values(SPORTS_CONFIG).filter(sport => sport.type === 'team');
}

export function getIndividualSports(): SportConfig[] {
  return Object.values(SPORTS_CONFIG).filter(sport => sport.type === 'individual');
}

export function getAllSports(): SportConfig[] {
  return Object.values(SPORTS_CONFIG);
}

export function getSportIds(): string[] {
  return Object.keys(SPORTS_CONFIG);
}

// Default sports for new users
export const DEFAULT_ENABLED_SPORTS = ['nhl']; // NHL is primary for this dashboard

// Category display order
export const CATEGORY_ORDER: SportCategory[] = ['pro', 'college', 'soccer', 'individual'];

export const CATEGORY_LABELS: Record<SportCategory, string> = {
  pro: 'Professional',
  college: 'College',
  soccer: 'Soccer',
  individual: 'Individual Sports',
};
